### PR TITLE
Allow spree user

### LINKED ISSUE #15: Incompatible with spree_auth_devise
Hello,

I'm attempting to use your alchemy_spree plugin with spree commerce version 2.3.2. There seems to be a incompatibility between alchemy-devise and spree_auth_devise. Alchemy-devise depends on devise "~> 3.0.0", and alchemy_spree depends on '~> 3.2.3', I can get bundler working correctly if I remove spree_auth_devise, but then I lose my /login route, and thus the login capability for my customers. Is there an easy way to get the two working together that I'm not seeing? 

Thank you for your time!

### PR DESCRIPTION
**Pull request by tvdeyen**
This allows to use either alchemy user, spree user class or even custom user classes.

Closes #15

### CODE REVIEW

**Comment by robinboening** [comment]
I think its the right way to go and it looks good to me at the first glance. But lets see if @mtomov will come along with some feedback. :)

**Comment by wdspkr** [comment]
I tried the 3rd option, followed all the two guides as described in the README.
For the Alchemy authentication to work, I needed an additional `admin?` method, although I did NOT reference it in the `alchemy_roles` like the example 2.1.1 in the [alchemy guide] (http://guides.alchemy-cms.com/edge/custom_authentication.html) says.
Maybe that's worth a note in the README?

**Comment by tvdeyen** [comment]
@wdspkr no, it's not, because that is completely in the domain of your app and user class you are providing. The code is just an example. If you have or not have an `admin?` method is part of your specific user model class and is not mandatory for Alchemy. Alchemy only needs the `alchemy_roles` method to return an array of role names, that's it.

**Comment by wdspkr** [comment]
The `admin?` method is called here:
https://github.com/AlchemyCMS/alchemy_spree/blob/allow-spree-user/lib/alchemy/spree/ability.rb#L7

**Comment by tvdeyen** [comment]
@wdspkr you are right. This method has to be removed. Thanks.

**Comment by mtomov** [comment]
It is working really well. I have just replaced my patched version directly with your branch and all worked right away. I am using Spree 3.0.0.beta store & Alchemy master. Using set-up scenario #1 (use spree auth devise), all pages render fine. 

Thank you very much. I really like your commits and the descriptions in the readme. Now the integration between Spree & Alchemy is seamless with no hidden decorators/engine set-ups.

On a side note, I want to also tell you guys how nice my experience working with Alchemy has been so far. Being totally new to it, everything works, nothing breaks out of a sudden, (and I did make a lot of layout, elements & config changes), there are no JS errors. Thank you for making it all work so well!

**Comment by tvdeyen** [comment]
Thank you for sharing this with us. It is very nice to here, that Alchemy works so well for you.

Best wishes

Thomas

**Pull request merged**
