### PR TITLE
Select any Spree taxon

### PR DESCRIPTION
**Pull request by mamhoff**
This is backported from one of our projects and allows any taxon to be selected
in the taxon editor partial.

### CODE REVIEW

**Comment by tvdeyen** [comment]
@mamhoff I'm not quite sure about this one. Maybe we could chat about you're motivation?

**Comment by mamhoff** [comment]
Before, the partial would only allow you to select taxons of first or second level, and if any taxons were named the same (but in different places of the hierarchy), as a user I would not be able to identify which taxon exactly I'm selecting. The change now shows all ancestors of the taxons and does not have option groups (which I personally didn't understand very well as it's impossible to map a hierarchy to option groups).

**Comment by tvdeyen** [comment]
Understood. I wasn't aware of the ancestors being displayed in a method called `pretty_name` (naming is not the strength of spree 🙄)

**Comment by tvdeyen** [comment]
@mamhoff would you be so kind and also open a PR on https://github.com/AlchemyCMS/alchemy-solidus

Thanks

**Pull request merged**
